### ISSUE TITLE
Language server doesn't start if opening xml files within neovim

### ISSUE THREAD

**Issue by nat212** [fannheyward/coc-xml#104]
If I open neovim, and then open an xml file from inside neovim (I have tested using NERDTree, Denite, and `:e pom.xml`) the language server does not get started. However, if I open the file with neovim on the command line (i.e `nvim pom.xml`), it does start. XML commands also aren't available when opening files from within. A simple workaround I have found is to call `:CocInstall coc-xml`, which starts the language server, but it's very annoying to have to do this each time.

**Comment by fannheyward** [comment]
Try `:CocUpdate` to upgrade.
