### ISSUE TITLE
Folding of xml files

### ISSUE THREAD

**Issue by the42** [fannheyward/coc-xml#114]
coc-xml should support folding of xml files?

When I run ` :%fold`, the error message is 'Cannot create fold with current 'foldmethod'

When I run `:call CocAction('fold')` the error message is foldmethod option should be manual

When I `:set foldmethod=manual` and re-run the Action, only one fold level below the top-level element is created.

How is XML-folding supposed to work with this plugin?

**Comment by fannheyward** [comment]
Please upgrade your coc.nvim also https://github.com/neoclide/coc.nvim/pull/1763
