### ISSUE TITLE
[coc-xml] Java runtime could not be located, Get the Java Development Kit?

### ISSUE THREAD

**Issue by horseinthesky** [fannheyward/coc-xml#135]
```
[coc-xml] Java runtime could not be located, Get the Java Development Kit?:
1. Yes
2. No
Type number and <Enter> or click with mouse (empty cancels):
```
What is this and what does it want?

**Comment by fannheyward** [comment]
coc-xml can't find Java from your env, set `$JAVA_HOME` in your env or set `xml.java.home` in `coc-settings.json`

**Comment by horseinthesky** [comment]
@fannheyward 
I'm sorry to bother but could you pls be a little bit more specific.
I'm on Ubuntu 18.04. Installed `openjdk-11-jdk` package
```
whereis java
java: /usr/bin/java /usr/share/java /usr/share/man/man1/java.1.gz
```
and put
```
"xml.java.home": "/usr/bin/java"
```
to `coc-settings.json`

And now is says:
```
[coc-xml] The xml.java.home variable defined in settings does not point to a JDK., Get the Java Develop
ment Kit?:
1. Yes
2. No
Type number and <Enter> or click with mouse (empty cancels):
```

**Comment by fannheyward** [comment]
Sorry for the delay.

coc-xml needs JDK to run, follows these orders to resole:

1. `xml.java.home` in coc-settings.json
2. `java.home`
3. `JAVA_HOME` in your env
4. `JDK_HOME` in your env

For your first error, coc-xml can't find in any above.

For your second error, `The xml.java.home variable defined in settings does not point to a JDK`, coc-xml can't find `bin` folder in your java_home.

For example, my `JAVA_HOME` is `JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home`, there are `bin` `jre` `lib` folders in it.

**Comment by horseinthesky** [comment]
@fannheyward 
Thanks a lot. I've just put
```
"xml.java.home": "/usr"
```
and it made extension happy.

One more thing: it now complains about first XML tag in my doc
![image](https://user-images.githubusercontent.com/19948672/89125165-17326780-d4e5-11ea-9bba-27395c7be1ef.png)

I've tried to put:
```
"xml.validation.enabled": false
```
and
```
"xml.validation.noGrammar": "ignore"
```
to coc-settings but it didn't fix this.
