### ISSUE TITLE
"xml.server.vmargs" not working

### ISSUE THREAD

**Issue by borisbrodski** [fannheyward/coc-xml#141]
The configuration key `xml.server.vmargs` isn't taking effect.

My investigations showed, that the value of the `xml.server.vmargs` is being put after the `-jar .../org.eclipse.lemminx-0.13.1-uber.jar` JVM argument and not before.

Example (coc-settings.json):

	"xml.server.vmargs": "-Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=8080"

Results in the process java.exe being executed with

    <path>\bin\java.exe -jar C:\Users\me\AppData\Local\coc\extensions\coc-xml-data\org.eclipse.lemminx-0.13.1-uber.jar -DwatchParentProcess=false -noverify -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=8080

Note: All arguments before `-jar` are the JVM-arguments, all arguments after `-jar` are the application arguments.

Note2: It could make sence to add one additional `coc-setting.json`-argument to specify application arguments.

**Comment by fannheyward** [comment]
Thank you for your report, please upgrade to v1.12.2

**Comment by borisbrodski** [comment]
Wow, that was a very _quick_ fix indeed! Thank you 👍
