### ISSUE TITLE
xml server crashed

### ISSUE THREAD

**Issue by srillia** [fannheyward/coc-xml#191]
[coc.nvim] The "xml" server crashed 5 times in the last 3 minutes. The server will not be restarted.

JAVA_HOME exist, jdk11.

**Comment by srillia** [comment]
**:CocCommand workspace.showOutput** ,  noting output

**Comment by fannheyward** [comment]
Remove LemMinX jar in `~/.config/coc/extensions/coc-xml-data` and try to download again, looks like your LemMinX file is broken.

**Comment by srillia** [comment]
@fannheyward yeh! , delete the **LemMinx** jar,re-download ,every all right,thanks. but ,at the beginning ,**CocInstall coc-xml** can't not work directly, should delete manually?

**Comment by fannheyward** [comment]
After you installed coc-xml, when you first time open an XML file, coc-xml will download the latest LemMinx. Maybe there is something wrong at the download. I'll improve this to delete the broken downloaded file.
