### ISSUE TITLE
Starting client Failed - Cannot read property 'reader' of undefined

### ISSUE THREAD

**Issue by yngwi** [fannheyward/coc-xml#31]
Hi,
I'm trying to use the language server on Windows 10 with Java 11 (Adopt-Open, I also tried Java 12) and the server (client) doesn't seem to start. When I display the XML output with CocList I get the following error (I removed the home path from the message below):

```
[Error  - 11:25:36] Starting client failed: 
TypeError: Cannot read property 'reader' of undefined
    at C:\[home]\.vim\plugged\coc.nvim\lib\language-client\client.js:2187:48
```

Is there a way I can fix this?
Thanks!
Daniel

**Comment by fannheyward** [comment]
`reader` is property of `transports`, looks like the server connection was not successfully established.

Run `java -jar [home]/coc/extensions/coc-xml-data/org.eclipse.lsp4xml-0.8.0-uber.jar` to check lsp4xml server is broken or not.

**Comment by yngwi** [comment]
Thanks for your answer!

I tried it and the jar gets started, there is no further error message. The console looks like this:

![image](https://user-images.githubusercontent.com/963440/62710554-cf732000-b9f7-11e9-973c-cc4510eac8ea.png)

**Comment by fannheyward** [comment]
I have tried OpenJDK 11 & 12 on macOS and all works. Don't known what's went wrong.

**Comment by yngwi** [comment]
I wonder what's wrong here. I have now tried to only install neccessary parts in a clean Windows 10 Sandbox and I get the same error (see screenshot below). I have only installed chocolatey, adoptopenjdk 12, nodejs, git and neovim incl. coc and coc-xml. I also tried it with different Java versions with the same result. Did you try it on Windows or Linux?

![image](https://user-images.githubusercontent.com/963440/62798105-be9cda00-badd-11e9-8fb2-871f02d5bfb8.png)

**Comment by yngwi** [comment]
Hi,
today I tried coc-xml on a brand new ubuntu vm and there everything works. So apparantly there are problems on Windows machines. Is there any way to find out why this doesn't work on Windows? As I have now seen on Linux the Languageserver works great and I really would like to use it. Thanks you!

**Comment by fannheyward** [comment]
Glad to hear it works for you.

**Comment by yngwi** [comment]
Hi, what I wanted to say is that it **doesn't work on windows**, only on linux and apparantly on macOs. I am unfortunately not an expert on the subject but do you think there might be a bug in how the lanugage server is called by coc-xml on Windows?

**Comment by fannheyward** [comment]
Got it. Maybe there is something wrong with client on Windows, I'll check it later.

**Comment by yngwi** [comment]
Great, thank you!

**Comment by yngwi** [comment]
Hi again. I just wanted to tell you that a similar issue with regards to Java has just been resolved by the authors of the coc-java plugin. See [here](https://github.com/neoclide/coc-java/issues/33) for the related issue. Maybe the problem with coc-xml has a similar solution?

Kind regards,
Daniel

**Comment by fannheyward** [comment]
@yngwi Thanks for your feedback, I have fixed this issue on Windows.
