### ISSUE TITLE
Not able to get latest language server version due to proxy issue

### ISSUE THREAD

**Issue by perfectspr** [fannheyward/coc-xml#38]
I'm behind a proxy and not able to  download latest language server, because it cloud not download the maven-metadata.xml file.

In the "getLatestVersion" function in downloader.ts file:
```typescript
const resp = await got(_url, {agent: agent});
```
"got" library needs an agent to download the maven-metadata.xml file.

**Comment by fannheyward** [comment]
fixed in https://github.com/fannheyward/coc-xml/commit/727c7f38c966e0d18a6c2e83e862e5527a966df3

Run `:CocUpdate` to latest coc-xml 1.6.1
