### ISSUE TITLE
Is there openjdk support?

### ISSUE THREAD

**Issue by AzimovParviz** [fannheyward/coc-xml#421]
Hello. i provided path to openjdk (found by $ which java) in coc-settings.json
`"java.home": "/usr/local/opt/openjdk@17/bin/java"`
 and when i open a xml file in neovim, I get this prompt that sends me to Oracle's download page for Java 17-19. Is there something else I forgot to do or open-jdk is not supported ?
<img width="883" alt="image" src="https://user-images.githubusercontent.com/37579085/216590594-feb63d28-ee11-497a-9749-3250cd986c37.png">

**Comment by fannheyward** [comment]
OpenJDK is supported, maybe something is broken, will check it ASAP.

**Comment by fannheyward** [comment]
Use `"java.home": "/usr/local/opt/openjdk@17`, without `bin/java`.

You can get `java.home` from `java -XshowSettings:properties -version 2>&1 | grep java.home`
