### ISSUE TITLE
[feature] Provide a xml.schemas to allow user swtich json schema?

### ISSUE THREAD

**Issue by Freed-Wu** [fannheyward/coc-xml#455]
Does coc-xml support [json schema](https://www.schemastore.org/json/)? Can coc-xml provide a xml.schemas to allow user switch json schema like [coc-yaml](https://github.com/neoclide/coc-yaml)?

> yaml.schemas: Helps you associate schemas with files in a glob pattern

**Comment by fannheyward** [comment]
Use `xml.catalogs`.
