### ISSUE TITLE
[question] how to disable the warning of invalid path of settings?

### ISSUE THREAD

**Issue by Freed-Wu** [fannheyward/coc-xml#464]
I have two machines, in machine A, dbus's catalog.xml is `/usr/share/xml/dbus/catalog.xml`, in machine B, it is `/run/current-system/sw/share/xml/dbus-1/catalog.xml`.

```json
  "xml.catalogs": [
    "/usr/share/xml/dbus/catalog.xml",
    "/run/current-system/sw/share/xml/dbus-1/catalog.xml"
  ],
```

However, in machine B:

```
[coc.nvim] Invalid path for setting 'xml.catalogs': "/usr/share/xml/dbus-1/catalog.xml"
```

in machine A:

```
[coc.nvim] Invalid path for setting 'xml.catalogs': "/run/current-system/sw/share/xml/dbus-1/catalog.xml"
```

Any method to disable the warning?

**Comment by fannheyward** [comment]
This warning was sent by server https://github.com/eclipse/lemminx/blob/d1d67ec09ad8ded638fc7c8ce1f52b72b33b8ec9/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/client/InvalidPathWarner.java#L65 , I don't think there's any way to disable it by now.
