### ISSUE TITLE
'End with "</ENDTAG>" completion

### ISSUE THREAD

**Issue by m42e** [fannheyward/coc-xml#60]
Hi,

I really appreciate the work you've done. It really helps a lot especially when dealing with a complex xml schema. But I notices, that when I try to close a tag, it shows me the last entries here:

<img width="320" alt="Bildschirmfoto 2019-10-04 um 10 55 15" src="https://user-images.githubusercontent.com/2410802/66194769-7ccf8080-e695-11e9-974a-578809d0b4e9.png">

The completion includes the whole text 
<img width="291" alt="Bildschirmfoto 2019-10-04 um 10 56 28" src="https://user-images.githubusercontent.com/2410802/66194821-a092c680-e695-11e9-9318-786bb18946b0.png">

Which is not exactly what I would expect.

## versions

vim version: NVIM v0.4.2
node version: v11.10.0
coc.nvim version: 0.0.74-a84f813105
## Output channel: XML Language Server

Okt. 04, 2019 10:49:16 VORM. org.eclipse.lsp4xml.XMLLanguageServer initialize
INFO: Initializing LSP4XML server 0.9.0-20190927-0726 with /Library/Java/JavaVirtualMachines/openjdk-12.0.1.jdk/Contents/Home
[Info  - 10:49:16 AM] Okt. 04, 2019 10:49:16 org.eclipse.lsp4xml.logs.LogHelper initializeRootLogger()
Message: Log file could not be created, path not provided

**Comment by fannheyward** [comment]
Can't reproduce this error, can you provide a minimal XML file that can reproduce this error? And a minimal vimrc is welcome.

**Comment by CoffeeCoder1** [comment]
I have been able to reproduce this by two methods.
1. Have three or more tags that can be closed, like this
````XML
<tag1>
    <tag2>
        <tag3>
````
When you try to close `<tag3>`, it will result in `<End with '</tag3>'>`.
2. Close a tag after typing a `/`
Type
````XML
<tag1>
</
````
and try to complete `<tag1>` after typing `</`. It will result in `<End with '</tag1>'>`.

**Comment by ZreXoc** [comment]
Any solution? Get the same error.

![image](https://github.com/fannheyward/coc-xml/assets/61901461/db154a41-5056-4c88-b83d-294de1e67e02)
![image](https://github.com/fannheyward/coc-xml/assets/61901461/2de792e4-332e-48c4-b617-8994f9d7d3af)

**Comment by iselind** [comment]
I get this as well
